spring:
  application:
    name: graphql-course

  profiles:
    active: ${SPRING_PROFILE}

  threads:
    virtual:
      enabled: true

  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /subscription

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
